GET {{Server_HostAddress}}/Authentication/simple-test
Cookie: access_token=

###
POST {{Server_HostAddress}}/Authentication/jwt/login
Content-Type: application/json

{
  "email": "some_email_here",
  "password": "My_dev_passw0rd"
}